### ISSUE TITLE
Suggestion: Allow us to specify winning number

### ISSUE THREAD

**Issue by jvence** [matthewlein/jQuery-jSlots#1]
This is more of a suggestion or question on how we can modify the code to allow us to specify the winning number beforehand and then have it spin to this number?
Many thanks for this great piece of code.

**Comment by matthewlein** [comment]
Hello and thanks.

The nature of a slot machine is randomness...so I didn't really think about it while I was building it.

Line 164
https://github.com/matthewlein/jQuery-jSlots/blob/3e1aecf1df68a4fa100dee932ed1f4bdab30ef00/jquery.jSlots.js#L164
is where it sets a random index number to spin to. you'd have to replace this with a set number, or an array.

I don't keep track of the slots indexes, so you'd probably do something like

var endingPos = [1,2,3] somewhere at the top

and then at 164 replace the random with something like endingPos[ $(that).index(allSlots) ]

which should give you the index of that slot within the allSlots array, and so should pull the appropriate number from endingPos.

This is 100% untested and off the top of my head, so it probably won't work as is, but should get you close.

**Comment by jvence** [comment]
Thanks so much for your help. I'm almost there except that:

var ii=$(that).index(that.allSlots);
var endNum = endingPos[ii];

endNum is 'undefined' as ii is equal to -1

Thanks for your help

**Comment by jvence** [comment]
For anyone who is interested, the solution is: var i=$(base.allSlots).index($(that));
