### ISSUE TITLE
Get the selected <li>

### ISSUE THREAD

**Issue by byeze** [matthewlein/jQuery-jSlots#15]
I need the result of the spin, for example:

```
<ul class="slot">
     <li>a</li>
     <li>b</li>
</ul>
```

Part of js code:

```
onWin: function() {
   alert("Selected li #" + selectedLi);
},
```

And for example, I pressed the button and the first li (a) is the selected, but in the js code, I dont know hot to get the selected li.

**Comment by matthewlein** [comment]
From the onWin comments: `It is passed (winCount:Number, winners:Array, finalNumbers:Array)`

So your example would need to explicitly ask for those params `onWin: function(winCount, winners, finalNumbers)`, then you'll have access to them in the function body to do whatever you want.
`finalNumbers gives the index of the li each slot stopped on in order.`

Unrelated, you'll get a lot more bang for your buck using `console.log` vs alert, which will print to the console. It's the best!
