### ISSUE TITLE
Do not clone only the first li item

### ISSUE THREAD

**Issue by marvink** [matthewlein/jQuery-jSlots#5]
you should clone:

$list.find('li').clone().appendTo($list);

instead of 

$li.clone().appendTo($list);

otherwise the first letter has a bigger chance to win.

**Comment by matthewlein** [comment]
Hello,

Just looking back at this. I'm fairly sure it is accounted for in the 1-based index. Its duplicated so the animation looks good. I don't really like the 1-based index idea, but thats how I did it and I don't really have time/reason to rework it.

Thanks for looking out though.

Matt
