### ISSUE TITLE
.slot unordered-list margin/padding issue

### ISSUE THREAD

**Issue by erichoco** [matthewlein/jQuery-jSlots#6]
Hello Matthew, 

First of all, thanks for creating this nice project. It's quite clear and easy for us to use this animation. But I run into some positioning issues while I am trying to modify the margin and padding of the uls of class ".slot". When they are set to 0, as the examples, the final result looks good. But as I modify their value, the three digits of the final result don't seem to be placed at their initial positions. And sometimes, they aren't vertically-aligned as well. Is there any work around? Or this is simply one of constraint? If so, maybe it should be mentioned in the readme file. Thanks.

**Comment by erichoco** [comment]
Oops I found the problem. I am getting it all wrong. It has nothing to do with margin and padding but the size of li elements. I tried to modify li elements after calling jSlots, which has had already store the height and width of the original li elements. As a result, it was using the old values to position the three digits when the "finish" function was called. Sorry about it.

**Comment by matthewlein** [comment]
Gotcha. Glad you figured it out :)

In the future, for any project, if you think you have a bug you should create a very simple test case on JSfiddle or Codepen so the author (and you) can isolate the problem. Otherwise we are flying blind.
