### ISSUE TITLE
start on mouse over or another event

### ISSUE THREAD

**Issue by arilishu** [matthewlein/jQuery-jSlots#7]
i want to play the slot, but not over an id click.
maybe, on document ready, by set interval or mouseover

**Comment by matthewlein** [comment]
Please ready the documentation, specifically the `spinEvent` and `spinner` options. That's what you'll use.

Mouseover is something like

```
spinEvent : 'mouseover',
```

Document ready would be:

```
spinner : document,
spinEvent : 'DOMContentLoaded',
```

**Comment by arilishu** [comment]
ok, thanks!
What about, inside setinterval.
i say, $('.fancy .slot').jSlots({...}) inside a function and the setinterval calling that function

Thanks.
