### ISSUE TITLE
is it possible to store the array of winning numbers so that after the box has finished spinning i can get all the numbers

### ISSUE THREAD

**Issue by ramza1** [matthewlein/jQuery-jSlots#9]

**Comment by matthewlein** [comment]
Yes, either using onEnd or onWin depending on if you want only winning spins, or non-winning spins too.

Copied directly from the readme:
`onEnd : $.noop,      // Function: run on spin end. It is passed (finalNumbers:Array). finalNumbers gives the index of the li each slot stopped on in order.`
`onWin : $.noop,      // Function: run on winning number. It is passed (winCount:Number, winners:Array, finalNumbers:Array)`
